### ISSUE TITLE
Desse impl for char is unsound

### ISSUE THREAD

**Issue by MikailBag** [devashishdxt/desse#12]
Consider this function: https://github.com/devashishdxt/desse/blob/master/desse/src/desse.rs#L266
If I will pass incorect Unicode value, it will trigger UB. However, it mustn't because it is not declared as unsafe.

AFAIC this can only be fixed by introducing new trait fn, `deserialize_from_unchecked`

**Comment by devashishdxt** [comment]
Introducing a new trait function only for this usecase does not make much sense to me. There are two main options that I can think of:
- Return `Result` from `deserialize_from()`.
- Panic in scenarios where input is invalid.

What do you think?

**Comment by MikailBag** [comment]
I would vote for Result, because it provides user with more control of error handling (return, panic, log, or maybe unchecked unwrap). Also, in client-server scenario bytes can come from untrusted source, and server should return error to client rather than panic.

**Comment by devashishdxt** [comment]
Yes. `Result` makes more sense here.

**Comment by devashishdxt** [comment]
Closing this in favour of https://github.com/devashishdxt/desse/issues/13

**Comment by Shnatsel** [comment]
Since this triggers UB from safe code, could you file a security advisory at https://github.com/RustSec/advisory-db? This will let users of your crate check if they're depending on a vulnerable version and upgrade.
