### ISSUE TITLE
Support Option<T: DesseStatic + DesseSize>

### ISSUE THREAD

**Issue by jrmuizel** [devashishdxt/desse#17]
This would be pretty handy.

**Comment by djg** [comment]
I've been trying to implement this and I'm currently stuck on https://github.com/rust-lang/rust/issues/60551

**Comment by devashishdxt** [comment]
We wont be able to do this without proper support for const generics. Until then, we can figure out a way to implement `DesseDynamic` trait for `Option<T>` which will enable de/serialization of `Option<T>`.

I haven't pushed `DesseDynamic` trait in `master` branch as it has a lot of missing pieces. Its currently in `desse-dynamic` branch.

**Comment by devashishdxt** [comment]
Implemented `DesseDynamic` for `Option<T>` in https://github.com/devashishdxt/desse/commit/4a0239b8171812224e2c4eddb02ae8b1d54affe4.
