### ISSUE TITLE
desse = "0.2.1" : no `DesseStatic` in the root

### ISSUE THREAD

**Issue by gcxfd** [devashishdxt/desse#26]
![image](https://user-images.githubusercontent.com/69608605/122327297-36e94780-cf60-11eb-8cff-d94d0490e9a0.png)
see image above

**Comment by devashishdxt** [comment]
Thanks for opening this issue. In all probability, you're reading documentation for `master` branch and using `v0.2.1`. Please refer to documentation for `v0.2.1` [here](https://docs.rs/desse/0.2.1/desse/).

**Comment by gcxfd** [comment]
thanks very much .

IS DesseDynamic ready to use ? I see it in github test , but not write in documents
